name: CPP Azure Subnet Module
trigger: none
pr:
- main

resources:
  repositories:
  - repository: cppAzureDevOpsTemplates
    type: github
    name: hmcts/cpp-azure-devops-templates
    ref: 'EI-1799'
    endpoint: 'hmcts'

extends:
  template: pipelines/terratest.yaml@cppAzureDevOpsTemplates
  parameters:
    agentPool: "ubuntu-latest"
    azureServiceConnection: "ado_nonlive_workload_identity"
    terratestTimeout: "30"
    tfversion: 1.2.3
